env:
  browser: false
  es2021: true
extends: standard-with-typescript
parserOptions:
  project: tsconfig.json

rules:
  "@typescript-eslint/no-misused-promises":
    - error
    - checksVoidReturn: false
  "@typescript-eslint/prefer-nullish-coalescing":
    - off
  "@typescript-eslint/strict-boolean-expressions":
    - off
  "@typescript-eslint/restrict-template-expressions":
    - off
